import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ap-south-2comsl2axx.auth.ap-south-2.amazoncognito.com/login?client_id=242rfjjj7h9hsbcmno1vki01bb&redirect_uri=https://saas-staging-api.narad.io/auth/cognito-callback&response_type=code&scope=email+openid+profile+aws.cognito.signin.user.admin');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('heena.webosmotic+lumora');
  await page.getByRole('textbox', { name: 'Email address' }).press('ControlOrMeta+2');
  await page.getByRole('textbox', { name: 'Email address' }).fill('heena.webosmotic+lumora@gmail.com');
  await page.getByRole('textbox', { name: 'Email address' }).click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Verification code' }).click();
  await page.getByRole('textbox', { name: 'Verification code' }).fill('22225595');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('button', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'Billing' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).fill('test 12 -45 adress, char rastaa 523 test adress test adres235 test adresss ');
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).fill('test 12 -45 adress, char rastaa 523 test adress test adres235 test adresss test adress');
  await page.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: 'Gujarat' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).fill('surat');
  await page.getByRole('textbox', { name: 'Pin Code' }).click();
  await page.getByRole('textbox', { name: 'Pin Code' }).fill('395006');
  await page.getByRole('textbox', { name: 'Add GST Number' }).click();
  await page.getByRole('textbox', { name: 'Add GST Number' }).fill('09AAACH7409R1Z');
  await page.getByRole('textbox', { name: 'Add GST Number' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Add GST Number' }).fill('09AAACH7409R1ZZ');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Billing details updated').dblclick();
  await page.getByText('Billing details updated').dblclick();
  await page.getByText('Billing details updated').dblclick();
  await page.getByRole('alert').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Company' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByText('Oct 2026').click();
  await page.getByRole('textbox', { name: 'Company Name' }).fill('Lumora & Pvt Ltd test TEST');
  await page.getByRole('button', { name: 'Members' }).click();
  await page.getByRole('button', { name: 'Add Member' }).click();
  await page.getByText('New Member').click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('HEENA');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('NEW TEST');
  await page.getByRole('textbox', { name: 'Last Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email*' }).fill('heena.webosmotic+test_new1@gmail.com');
  await page.getByLabel('Add Member').getByText('Member', { exact: true }).click();
  await page.locator('#menu-').getByText('Member', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Member added successfully.').dblclick();
  await page.getByLabel('heena.webosmotic+test_new1@').click();
  await page.getByText('HHEENA NEW TEST').click();
  await page.getByRole('button', { name: 'More Actions' }).nth(3).click();
  await page.getByText('Edit Email Id').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'More Actions' }).nth(3).click();
  await page.getByText('Resend Onboarding Email').click();
  await page.getByText('A verification link has been').dblclick();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'More Actions' }).nth(3).click();
  await page.getByText('Delete Member').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByText('Member deleted successfully').dblclick();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Usage' }).click();
  await page.locator('div').filter({ hasText: /^October 16, 2025$/ }).click();
});