import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ap-south-2z4wvmykmm.auth.ap-south-2.amazoncognito.com/login?client_id=gt37poo1uas0l30b6cc466s6e&redirect_uri=https://saas-prod-api.narad.io/auth/cognito-callback&response_type=code&scope=email+openid+profile+aws.cognito.signin.user.admin');
  await page.getByRole('textbox', { name: 'Email address' }).fill('heena.webosmotic+');
  await page.getByRole('textbox', { name: 'Email address' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email address' }).fill('heena.webosmotic+A');
  await page.getByRole('textbox', { name: 'Email address' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email address' }).fill('heena.webosmotic+Admin2@gmail.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Try another way' }).click();
  await page.getByRole('radio', { name: 'Password', exact: true }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('N');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Narad123!');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Cabinet' }).click();
  await page.getByRole('button', { name: 'Policies' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByText('Upload Files').click();
  await page.getByRole('button', { name: 'Add' }).setInputFiles('Information-Security-Policy-EN.pdf');
  await page.getByText('File uploaded successfully').dblclick();
  await page.getByText('File uploaded successfully').dblclick();
  await page.getByText('File uploaded successfully').dblclick();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByLabel('Information-Security-Policy-EN').click();
  await page.locator('.MuiTableRow-root.MuiTableRow-hover.css-giid62 > td:nth-child(7) > .MuiStack-root.css-9fk72w > .MuiTypography-root > .MuiStack-root > .MuiBox-root > span > .MuiButtonBase-root').click();
  await page.getByText('Rename').click();
  await page.getByRole('textbox', { name: 'File Name*' }).fill('Information-Security-Policy-EN new');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.locator('.MuiTableRow-root.MuiTableRow-hover.css-giid62 > td:nth-child(7) > .MuiStack-root.css-9fk72w > .MuiTypography-root > .MuiStack-root > .MuiBox-root > span > .MuiButtonBase-root').click();
  await page.getByText('Delete').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Trust Center Beta' }).click();
  await page.getByRole('button', { name: 'Set Up' }).click();
  await page.getByRole('button', { name: 'Copy' }).first().click();
  await page1.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%253Ca%2Bhref%253D%2522https%253A%252F%252Fskyenter.saas-prod.narad.io%252Ftrust-center%2522%2Btarget%253D%2522_blank%2522%253ETrust%2BCenter%253C%252Fa%253E%26oq%3D%253Ca%2Bhref%253D%2522https%253A%252F%252Fskyenter.saas-prod.narad.io%252Ftrust-center%2522%2Btarget%253D%2522_blank%2522%253ETrust%2BCenter%253C%252Fa%253E%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBBzQ0N2owajGoAgCwAgA%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DLaDkaMfKHvGH4-EPzZyggAw&q=EgQ7kH7IGK3AkscGIjD8ajfhhitKQc6aHPRd2vL93hShu9yG3ahUv0S49xwFKCuww3Y7xEXkU077KeeSWq8yAVJaAUM');
  await page.getByRole('button', { name: 'Copy' }).nth(1).click();
  await page.getByRole('button', { name: 'Documents' }).click();
  await page.getByRole('button', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'Billing' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByText('Warehouse (North) | Sector 7 test adressAddress *').dblclick();
  await page.getByText('Warehouse (North) | Sector 7 test adressAddress *').dblclick();
  await page.getByRole('textbox', { name: 'Address *' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Address *' }).fill('test 12 -45 adress, char rastaa 523');
  await page.getByLabel('Edit Billing Details').getByText('India').click();
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByText('Gujarat').click();
  await page.getByRole('option', { name: 'Gujarat' }).click();
  await page.locator('.MuiBackdrop-root.MuiBackdrop-invisible').click();
  await page.getByRole('textbox', { name: 'City' }).fill('surat');
  await page.getByRole('textbox', { name: 'Pin Code' }).fill('395009');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Billing details updated').dblclick();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Company' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).fill('Skyenter test name');
  await page.getByRole('combobox', { name: 'Reminder 6 months' }).click();
  await page.getByRole('option', { name: '3 months' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Members' }).click();
  await page.getByRole('button', { name: 'Add Member' }).click();
  await page.getByText('New Member').click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('test');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('new member');
  await page.getByRole('textbox', { name: 'Last Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email*' }).fill('heena.webosmotic+member_0022@gmail.com');
  await page.getByRole('combobox').dblclick();
  await page.locator('#menu- span').filter({ hasText: /^Member$/ }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Member added successfully.').dblclick();
  await page.locator('button').nth(4).click();
  await page.getByLabel('Permission Restricted').locator('button').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Heena tester' }).click();
  await page.getByText('View Profile').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Heenaaaa');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Heenaaaaa');
  await page.getByRole('textbox', { name: 'Last Name' }).fill(' testeraa');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill(' tester');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).dblclick();

  await page.getByRole('textbox', { name: 'Last Name' }).fill('tester');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Heenaaaaa tester' }).click();
  await page.getByText('View Profile').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('button', { name: 'Upload profile photo' }).click();
  await page.getByRole('button', { name: 'Upload profile photo' }).setInputFiles('images.jpg');
  await page.locator('.cropper-face').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
});